import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import * as ImagePicker from "expo-image-picker";
import { router } from "expo-router";
import { useState } from "react";
import {
  ActivityIndicator,
  Alert,
  Platform,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

import { saveAnalysisSession } from "@/services/analysis-sessions";
import { analyzeVideo } from "@/services/kinetiq-api";
import {
  ACCENT_BORDER,
  APP_BG,
  APP_SHADOW,
  APP_SURFACE,
  APP_TEXT,
  APP_TEXT_MUTED,
  PURPLE,
  PURPLE_TINT_STRONG,
  SUCCESS,
  SUCCESS_BORDER,
  SUCCESS_SURFACE,
  WHITE,
} from "@/constants/colors";
import { useAuth } from "@/context/auth-context";
import { useDatabaseLiveValue } from "@/hooks/use-database";
import { formatUserId } from "@/utils/user";

const REQUIREMENTS = [
  "Side angle shot",
  "Good lighting",
  "5-15 seconds duration",
  "Full body visible",
];

const FILE_INFO = [
  "Phase scores are generated by the KinetiQ backend",
  "Analysis sessions are saved to Firebase Realtime Database",
  "Supported formats depend on the backend video codecs installed",
];

function showError(message: string) {
  if (Platform.OS === "web") {
    window.alert(message);
    return;
  }

  Alert.alert("Upload failed", message);
}

function BasketballUpload() {
  const { user } = useAuth();
  const userId = formatUserId(user?.sub);
  const { value: latestSessionId } = useDatabaseLiveValue<string>(
    `users/${userId}/analysis/activeSessionId`,
  );

  const [isSubmitting, setIsSubmitting] = useState(false);
  const [statusMessage, setStatusMessage] = useState<string | null>(null);
  const [selectedFileName, setSelectedFileName] = useState<string | null>(null);

  const handleUpload = async () => {
    setStatusMessage(null);

    const permission =
      await ImagePicker.requestMediaLibraryPermissionsAsync();

    if (!permission.granted) {
      showError("Media library access is required to pick a shot video.");
      return;
    }

    const pickerResult = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ["videos"],
      quality: 1,
      allowsEditing: false,
      selectionLimit: 1,
    });

    if (pickerResult.canceled) {
      return;
    }

    const asset = pickerResult.assets[0];

    if (!asset || asset.type !== "video") {
      showError("Please choose a video file to analyze.");
      return;
    }

    setSelectedFileName(asset.fileName ?? "Selected shot video");
    setIsSubmitting(true);

    try {
      setStatusMessage("Uploading your shot to KinetiQ...");
      const analysis = await analyzeVideo(asset);

      setStatusMessage("Saving your results to Firebase...");
      const session = await saveAnalysisSession({
        userId,
        asset,
        analysis,
      });

      router.push({
        pathname: "/shot-breakdown",
        params: { sessionId: session.id },
      });
    } catch (error) {
      const message =
        error instanceof Error
          ? error.message
          : "Something went wrong while analyzing your shot.";
      setStatusMessage(null);
      showError(message);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <ScrollView
      style={styles.scroll}
      contentContainerStyle={styles.scrollContent}
      showsVerticalScrollIndicator={false}
    >
      <View style={styles.card}>
        <View style={styles.dropZone}>
          <View style={styles.iconCircle}>
            {isSubmitting ? (
              <ActivityIndicator color={PURPLE} size="large" />
            ) : (
              <MaterialIcons name="videocam" size={34} color={PURPLE} />
            )}
          </View>
          <Text style={styles.chooseTitle}>Choose video</Text>
          <Text style={styles.chooseSub}>
            Upload a real shot clip and get backend-generated analysis
          </Text>

          <TouchableOpacity
            style={[styles.selectBtn, isSubmitting && styles.selectBtnDisabled]}
            activeOpacity={0.85}
            onPress={handleUpload}
            disabled={isSubmitting}
          >
            <MaterialIcons
              name={isSubmitting ? "sync" : "upload"}
              size={20}
              color={WHITE}
            />
            <Text style={styles.selectBtnText}>
              {isSubmitting ? "Analyzing..." : "Select File"}
            </Text>
          </TouchableOpacity>

          {selectedFileName ? (
            <Text style={styles.fileName}>{selectedFileName}</Text>
          ) : null}

          {statusMessage ? (
            <Text style={styles.statusMessage}>{statusMessage}</Text>
          ) : null}
        </View>

        <View style={styles.reqCard}>
          <Text style={styles.reqTitle}>Video Requirements</Text>
          {REQUIREMENTS.map((item) => (
            <View key={item} style={styles.reqRow}>
              <Text style={styles.reqBullet}>•</Text>
              <Text style={styles.reqText}>{item}</Text>
            </View>
          ))}
        </View>

        <View style={styles.infoSection}>
          {FILE_INFO.map((item) => (
            <View key={item} style={styles.infoRow}>
              <Text style={styles.infoBullet}>•</Text>
              <Text style={styles.infoText}>{item}</Text>
            </View>
          ))}
        </View>

        {latestSessionId ? (
          <TouchableOpacity
            style={styles.latestSessionButton}
            activeOpacity={0.85}
            onPress={() =>
              router.push({
                pathname: "/shot-breakdown",
                params: { sessionId: latestSessionId },
              })
            }
          >
            <MaterialIcons name="history" size={18} color={SUCCESS} />
            <Text style={styles.latestSessionText}>Open latest saved analysis</Text>
          </TouchableOpacity>
        ) : null}
      </View>
    </ScrollView>
  );
}

export default function UploadScreen() {
  const { user } = useAuth();
  const userId = formatUserId(user?.sub);
  const { value: activeSport } = useDatabaseLiveValue<string>(
    `users/${userId}/sports/active`,
  );

  const sport = activeSport ?? "Basketball";

  return (
    <SafeAreaView style={styles.safeArea}>
      {sport === "Basketball" ? (
        <BasketballUpload />
      ) : (
        <View style={styles.blank} />
      )}
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: APP_BG,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 40,
  },
  blank: {
    flex: 1,
    backgroundColor: APP_BG,
  },
  card: {
    backgroundColor: APP_SURFACE,
    borderRadius: 20,
    shadowColor: APP_SHADOW,
    shadowOpacity: 0.07,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
    overflow: "hidden",
  },
  dropZone: {
    margin: 16,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: ACCENT_BORDER,
    borderStyle: "dashed",
    alignItems: "center",
    paddingVertical: 36,
    paddingHorizontal: 24,
    gap: 10,
  },
  iconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: PURPLE_TINT_STRONG,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  chooseTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: APP_TEXT,
    letterSpacing: -0.3,
  },
  chooseSub: {
    fontSize: 15,
    color: APP_TEXT_MUTED,
    textAlign: "center",
    lineHeight: 22,
  },
  selectBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: PURPLE,
    paddingVertical: 15,
    paddingHorizontal: 36,
    borderRadius: 50,
    marginTop: 8,
  },
  selectBtnDisabled: {
    opacity: 0.7,
  },
  selectBtnText: {
    color: WHITE,
    fontSize: 16,
    fontWeight: "700",
  },
  fileName: {
    marginTop: 4,
    fontSize: 13,
    color: APP_TEXT,
    fontWeight: "600",
  },
  statusMessage: {
    marginTop: 4,
    fontSize: 13,
    color: PURPLE,
    textAlign: "center",
    lineHeight: 20,
  },
  reqCard: {
    marginHorizontal: 16,
    marginBottom: 16,
    backgroundColor: PURPLE_TINT_STRONG,
    borderRadius: 14,
    padding: 18,
    gap: 10,
  },
  reqTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: APP_TEXT,
    marginBottom: 2,
  },
  reqRow: {
    flexDirection: "row",
    gap: 10,
    alignItems: "flex-start",
  },
  reqBullet: {
    fontSize: 15,
    color: PURPLE,
    lineHeight: 22,
  },
  reqText: {
    fontSize: 15,
    color: PURPLE,
    flex: 1,
    lineHeight: 22,
  },
  infoSection: {
    paddingHorizontal: 20,
    paddingBottom: 16,
    gap: 10,
  },
  infoRow: {
    flexDirection: "row",
    gap: 10,
    alignItems: "flex-start",
  },
  infoBullet: {
    fontSize: 15,
    color: APP_TEXT_MUTED,
    lineHeight: 22,
  },
  infoText: {
    fontSize: 15,
    color: APP_TEXT_MUTED,
    flex: 1,
    lineHeight: 22,
  },
  latestSessionButton: {
    marginHorizontal: 16,
    marginBottom: 22,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: SUCCESS_SURFACE,
    borderWidth: 1,
    borderColor: SUCCESS_BORDER,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  latestSessionText: {
    color: SUCCESS,
    fontSize: 15,
    fontWeight: "700",
  },
});
